// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package Templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AboutMe() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"grid grid-cols-5\"><div class=\"introduction-home-container col-span-3\"><span>About Me</span><br><span class=\"gradient-fill text-5xl\">Cole Flenniken.</span><br><span>Building AI and Web Applications</span><p>Hi there! I'm a software developer with a deep passion for computer science—from low-level systems programming to cutting-edge AI research. Based in New England, I work at Textron on the Custom Applications and AI teams, creating robust solutions with C#/.NET, Python, and Azure cloud. My seven years in competitive mathematics and two in competitive programming fuel personal projects at the intersection of math, algorithms, and development. Fascinated by software architecture, I strive to build scalable, efficient systems. Currently, I’m honing my applied deep learning skills while completing my master’s, always eager to tackle the next challenge.</p></div><div class=\"col-span-2\"><div><div class=\"max-w-sm rounded overflow-hidden shadow-lg shadow-indigo border-color\"><img class=\"w-full\" src=\"static/img/pic1.JPG\"><div class=\"px-6 py-4\" style=\"background-color: var(--secondary-color);\"><div class=\"font-bold text-xl mb-2 primary-color\">Madeira, Porugal</div><p class=\"text-gwhite-700 text-base\">After finishing my undergrad, I had the opportunity to travel to Madeira an island of Portugal. It was the most beautiful place i've been and I can't recommend it enough!</p></div></div></div><div></div><div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
